apiVersion: v1
kind: Service
metadata:
  name: k8s-server-nodeport
spec:
  ports:
    - name: web-port
      nodePort: 31010
      port: 8080
      targetPort: 8080
  selector:
    app: k8s-server
  type: NodePort